#!/bin/sh
# SAUER_DATA should refer to the directory in which
# Sauerbraten data files are placed.
SAUER_DATA=./sauerbraten

# SAUER_USER_DATA should refer to the directory in which
# Sauerbraten user data files are placed.
SAUER_USER_DATA=./user

# OGZRAD_BIN should refer to the directory in which
# OGZ Radiant executable files are placed.
OGZRAD_BIN=./linux/build

# SYSTEM_NAME should be set to the name of your operating system.
#SYSTEM_NAME=Linux
SYSTEM_NAME=`uname -s`

# MACHINE_NAME should be set to the name of your processor.
#MACHINE_NAME=i686
MACHINE_NAME=`uname -m`

case ${SYSTEM_NAME} in
Linux)
  SYSTEM_NAME=linux_
  ;;
*)
  SYSTEM_NAME=unknown_
  ;;
esac

case ${MACHINE_NAME} in
i486|i586|i686)
  MACHINE_NAME=
  ;;
x86_64|amd64)
  MACHINE_NAME=64_
  ;;
*)
  if [ ${SYSTEM_NAME} != native_ ]
  then
    SYSTEM_NAME=native_
  fi
  MACHINE_NAME=
  ;;
esac

if [ -x ${OGZRAD_BIN}/native_client ]
then
  SYSTEM_NAME=native_
  MACHINE_NAME=
fi

if [ -x ${OGZRAD_BIN}/${SYSTEM_NAME}${MACHINE_NAME}client ]
then
  exec ${OGZRAD_BIN}/${SYSTEM_NAME}${MACHINE_NAME}client \
	-q${SAUER_USER_DATA} -k${SAUER_DATA} -logzradiant "$@"
else
  echo "ERROR: could not find pre-compiled binary file for your platform."
  echo "Looking for:" ${OGZRAD_BIN}/${SYSTEM_NAME}${MACHINE_NAME}client
  exit 1
fi
